config/routes.rb
Score::Application.routes.draw do
  resources :player

  root :to => 'player#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :name, :score
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
    @players = Player.all
  end
  
  def new
    @player = Player.new
  end
  
  def create
    @player = Player.new(params[:player])
    if @player.save
      @players = Player.all
      render "index"
    else
      render "new"
    end
  end
  
  def update
    player = Player.find(params[:player][:id])
    new_score = params[:player][:score].to_i + player.score.to_i
    player.update_attributes(score: new_score)

    @players = Player.all
    render "index"
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy

    @players = Player.all
    render "index"
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Score</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/player/index.html.erb
<h1>Hey look, this is index</h1>
<p><%= link_to "New Player", new_player_url %></p>

<% @players.each do |player| %>
  <p>Name:<%= player.name %>, Score:<%= player.score %></p>
  
  <%= form_for player do |f| %>
    <%= f.label :score %>:
    <%= f.text_field :score %><br />
    
    <%= f.hidden_field :id %>

    <%= f.submit %>
  <% end %>
  
  <%= link_to 'Destroy', player_path(player), :method => :delete %>

<% end %>

app/views/player/new.html.erb
<h1>add a new player</h1>
<%= @player.inspect %>

<%= form_for @player, url: {action: "create"} do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.submit %>
<% end %>